WIP: Upgrade from `mockito-all` `2.0.x` to `mockito-core` `2.34.4`
Per https://github.com/mockito/mockito/issues/324, `mockito-all` was deprecated in Mockito v2.0.0-beta.112 back in August 2016. This commit updates several places that were not compatible with the newer version of Mockito.

A remaining issue is the following error:
```
Mockito cannot mock this class: interface javax.naming.Context.

Underlying exception : java.lang.IllegalStateException: Error invoking java.lang.ClassLoader#defineClass
        at org.forgerock.audit.handlers.jms.JndiJmsContextManagerTest.testContextLoading(JndiJmsContextManagerTest.java:85)
Caused by: java.lang.IllegalStateException: Error invoking java.lang.ClassLoader#defineClass
        at org.forgerock.audit.handlers.jms.JndiJmsContextManagerTest.testContextLoading(JndiJmsContextManagerTest.java:85)
Caused by: java.lang.NoClassDefFoundError: javax/naming/Context
        at org.forgerock.audit.handlers.jms.JndiJmsContextManagerTest.testContextLoading(JndiJmsContextManagerTest.java:85)
```

This is being tracked by https://github.com/WrenSecurity/wrensec-commons/issues/17.